---
- name: install php
  action: '{{ ansible_pkg_mgr }} name={{ item }} state=latest'
  with_items:
    - php
    #- php56w
    #- php56w-opcache
    - php-mysql
    - php-common
    - php-curl
    - php-mbstring
    - php-xml
    - php-gd
    #- php-mysqlnd
    - php-pear
    - php-pecl-memcached
    - php-xmlrpc
    - php-pclzip
  notify: restart httpd.service
